version: 2

models:
  - name: stg_greenery__addresses
    description: Address info such as street address and zip code

  - name: stg_greenery__events
    description: User interaction events such as add to cart, page view, etc.

  - name: stg_greenery__order_items

  - name: stg_greenery__orders

  - name: stg_greenery__products

  - name: stg_greenery__promos

  - name: stg_greenery__users    